[servers]
222.222.222.222 ansible_user=root ansible_ssh_private_key_file=/home/ваше_имя/.ssh/ваш_SSH_ключ     # Замените IP на IP вашего сервера, если у вас пароль, то замените "ansible_ssh_private_key_file" на "ansible_password=ваш_пароль"
